// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: bookstore.proto

// 定义当前文件使用的 Protocol Buffers 语法版本为 proto3
// proto3 是 Google 推出的更简洁、更易用的版本，推荐用于新项目

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 书架资源。
type Shelf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 书架的唯一 id。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 书架上的主题(小说、诗歌等)。
	Theme string `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	// 书架的大小
	Size          int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_bookstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shelf.ProtoReflect.Descriptor instead.
func (*Shelf) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{0}
}

func (x *Shelf) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shelf) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *Shelf) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 图书资源。
type Book struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 图书的唯一 id。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 图书的作者。
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// 书名
	Title         string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_bookstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// 调用 ListShelves 返回的响应消息。
type ListShelvesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 书店里的书架。
	Shelves       []*Shelf `protobuf:"bytes,1,rep,name=shelves,proto3" json:"shelves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShelvesResponse) Reset() {
	*x = ListShelvesResponse{}
	mi := &file_bookstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShelvesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShelvesResponse) ProtoMessage() {}

func (x *ListShelvesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShelvesResponse.ProtoReflect.Descriptor instead.
func (*ListShelvesResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{2}
}

func (x *ListShelvesResponse) GetShelves() []*Shelf {
	if x != nil {
		return x.Shelves
	}
	return nil
}

// CreateShelf 方法的请求消息。
type CreateShelfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要创建的书架数据
	Shelf         *Shelf `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfRequest) Reset() {
	*x = CreateShelfRequest{}
	mi := &file_bookstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfRequest) ProtoMessage() {}

func (x *CreateShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfRequest.ProtoReflect.Descriptor instead.
func (*CreateShelfRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShelfRequest) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

// GetShelf 方法的请求消息。
type GetShelfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要检索的书架的ID。
	Shelf         int64 `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfRequest) Reset() {
	*x = GetShelfRequest{}
	mi := &file_bookstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfRequest) ProtoMessage() {}

func (x *GetShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfRequest.ProtoReflect.Descriptor instead.
func (*GetShelfRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{4}
}

func (x *GetShelfRequest) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

// DeleteShelf 方法的请求消息。
type DeleteShelfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要删除的书架的ID
	Shelf         int64 `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShelfRequest) Reset() {
	*x = DeleteShelfRequest{}
	mi := &file_bookstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShelfRequest) ProtoMessage() {}

func (x *DeleteShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShelfRequest.ProtoReflect.Descriptor instead.
func (*DeleteShelfRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteShelfRequest) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

// Request message for ListBooks method.
type ListBooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the shelf which books to list.
	Shelf         int64 `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_bookstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{6}
}

func (x *ListBooksRequest) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

// ListBooks 方法的请求消息。
type ListBooksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 书架上的图书。
	Books         []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_bookstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{7}
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

// CreateBook 方法的请求消息。
type CreateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要在其上创建图书的书架的 ID。
	Shelf int64 `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	// 在书架上创建的图书数据。
	Book          *Book `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_bookstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBookRequest) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

var File_bookstore_proto protoreflect.FileDescriptor

const file_bookstore_proto_rawDesc = "" +
	"\n" +
	"\x0fbookstore.proto\x12\tbookstore\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"A\n" +
	"\x05Shelf\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"D\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"A\n" +
	"\x13ListShelvesResponse\x12*\n" +
	"\ashelves\x18\x01 \x03(\v2\x10.bookstore.ShelfR\ashelves\"<\n" +
	"\x12CreateShelfRequest\x12&\n" +
	"\x05shelf\x18\x01 \x01(\v2\x10.bookstore.ShelfR\x05shelf\"'\n" +
	"\x0fGetShelfRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\"*\n" +
	"\x12DeleteShelfRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\"(\n" +
	"\x10ListBooksRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\":\n" +
	"\x11ListBooksResponse\x12%\n" +
	"\x05books\x18\x01 \x03(\v2\x0f.bookstore.BookR\x05books\"N\n" +
	"\x11CreateBookRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\x12#\n" +
	"\x04book\x18\x02 \x01(\v2\x0f.bookstore.BookR\x04book2\xad\x04\n" +
	"\tBookstore\x12Z\n" +
	"\vListShelves\x12\x16.google.protobuf.Empty\x1a\x1e.bookstore.ListShelvesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/shelves\x12Z\n" +
	"\vCreateShelf\x12\x1d.bookstore.CreateShelfRequest\x1a\x10.bookstore.Shelf\"\x1a\x82\xd3\xe4\x93\x02\x14:\x05shelf\"\v/v1/shelves\x12U\n" +
	"\bGetShelf\x12\x1a.bookstore.GetShelfRequest\x1a\x10.bookstore.Shelf\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/shelves/{shelf}\x12a\n" +
	"\vDeleteShelf\x12\x1d.bookstore.DeleteShelfRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/shelves/{shelf}\x12H\n" +
	"\tListBooks\x12\x1b.bookstore.ListBooksRequest\x1a\x1c.bookstore.ListBooksResponse\"\x00\x12d\n" +
	"\n" +
	"CreateBook\x12\x1c.bookstore.CreateBookRequest\x1a\x0f.bookstore.Book\"'\x82\xd3\xe4\x93\x02!:\x04book\"\x19/v1/shelves/{shelf}/booksBG\n" +
	"%com.liwenzhou.blog.examples.bookstoreB\x0eBookstoreProtoP\x01Z\fbookstore/pbb\x06proto3"

var (
	file_bookstore_proto_rawDescOnce sync.Once
	file_bookstore_proto_rawDescData []byte
)

func file_bookstore_proto_rawDescGZIP() []byte {
	file_bookstore_proto_rawDescOnce.Do(func() {
		file_bookstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookstore_proto_rawDesc), len(file_bookstore_proto_rawDesc)))
	})
	return file_bookstore_proto_rawDescData
}

var file_bookstore_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bookstore_proto_goTypes = []any{
	(*Shelf)(nil),               // 0: bookstore.Shelf
	(*Book)(nil),                // 1: bookstore.Book
	(*ListShelvesResponse)(nil), // 2: bookstore.ListShelvesResponse
	(*CreateShelfRequest)(nil),  // 3: bookstore.CreateShelfRequest
	(*GetShelfRequest)(nil),     // 4: bookstore.GetShelfRequest
	(*DeleteShelfRequest)(nil),  // 5: bookstore.DeleteShelfRequest
	(*ListBooksRequest)(nil),    // 6: bookstore.ListBooksRequest
	(*ListBooksResponse)(nil),   // 7: bookstore.ListBooksResponse
	(*CreateBookRequest)(nil),   // 8: bookstore.CreateBookRequest
	(*emptypb.Empty)(nil),       // 9: google.protobuf.Empty
}
var file_bookstore_proto_depIdxs = []int32{
	0,  // 0: bookstore.ListShelvesResponse.shelves:type_name -> bookstore.Shelf
	0,  // 1: bookstore.CreateShelfRequest.shelf:type_name -> bookstore.Shelf
	1,  // 2: bookstore.ListBooksResponse.books:type_name -> bookstore.Book
	1,  // 3: bookstore.CreateBookRequest.book:type_name -> bookstore.Book
	9,  // 4: bookstore.Bookstore.ListShelves:input_type -> google.protobuf.Empty
	3,  // 5: bookstore.Bookstore.CreateShelf:input_type -> bookstore.CreateShelfRequest
	4,  // 6: bookstore.Bookstore.GetShelf:input_type -> bookstore.GetShelfRequest
	5,  // 7: bookstore.Bookstore.DeleteShelf:input_type -> bookstore.DeleteShelfRequest
	6,  // 8: bookstore.Bookstore.ListBooks:input_type -> bookstore.ListBooksRequest
	8,  // 9: bookstore.Bookstore.CreateBook:input_type -> bookstore.CreateBookRequest
	2,  // 10: bookstore.Bookstore.ListShelves:output_type -> bookstore.ListShelvesResponse
	0,  // 11: bookstore.Bookstore.CreateShelf:output_type -> bookstore.Shelf
	0,  // 12: bookstore.Bookstore.GetShelf:output_type -> bookstore.Shelf
	9,  // 13: bookstore.Bookstore.DeleteShelf:output_type -> google.protobuf.Empty
	7,  // 14: bookstore.Bookstore.ListBooks:output_type -> bookstore.ListBooksResponse
	1,  // 15: bookstore.Bookstore.CreateBook:output_type -> bookstore.Book
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bookstore_proto_init() }
func file_bookstore_proto_init() {
	if File_bookstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookstore_proto_rawDesc), len(file_bookstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookstore_proto_goTypes,
		DependencyIndexes: file_bookstore_proto_depIdxs,
		MessageInfos:      file_bookstore_proto_msgTypes,
	}.Build()
	File_bookstore_proto = out.File
	file_bookstore_proto_goTypes = nil
	file_bookstore_proto_depIdxs = nil
}
