// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: notice.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoticeReaderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Msg   string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are valid to be assigned to NoticeWay:
	//
	//	*NoticeReaderRequest_Email
	//	*NoticeReaderRequest_Phone
	NoticeWay     isNoticeReaderRequest_NoticeWay `protobuf_oneof:"notice_way"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeReaderRequest) Reset() {
	*x = NoticeReaderRequest{}
	mi := &file_notice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeReaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeReaderRequest) ProtoMessage() {}

func (x *NoticeReaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeReaderRequest.ProtoReflect.Descriptor instead.
func (*NoticeReaderRequest) Descriptor() ([]byte, []int) {
	return file_notice_proto_rawDescGZIP(), []int{0}
}

func (x *NoticeReaderRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NoticeReaderRequest) GetNoticeWay() isNoticeReaderRequest_NoticeWay {
	if x != nil {
		return x.NoticeWay
	}
	return nil
}

func (x *NoticeReaderRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.NoticeWay.(*NoticeReaderRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *NoticeReaderRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.NoticeWay.(*NoticeReaderRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isNoticeReaderRequest_NoticeWay interface {
	isNoticeReaderRequest_NoticeWay()
}

type NoticeReaderRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type NoticeReaderRequest_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*NoticeReaderRequest_Email) isNoticeReaderRequest_NoticeWay() {}

func (*NoticeReaderRequest_Phone) isNoticeReaderRequest_NoticeWay() {}

type Book struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Title         string                  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Price         *int64                  `protobuf:"varint,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Price2        *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=price2,proto3" json:"price2,omitempty"`
	Memo          *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_notice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_notice_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *Book) GetPrice2() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Price2
	}
	return nil
}

func (x *Book) GetMemo() *wrapperspb.StringValue {
	if x != nil {
		return x.Memo
	}
	return nil
}

var File_notice_proto protoreflect.FileDescriptor

const file_notice_proto_rawDesc = "" +
	"\n" +
	"\fnotice.proto\x12\x03api\x1a\x1egoogle/protobuf/wrappers.proto\"e\n" +
	"\x13NoticeReaderRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phoneB\f\n" +
	"\n" +
	"notice_way\"\xc1\x01\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x03H\x00R\x05price\x88\x01\x01\x124\n" +
	"\x06price2\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\x06price2\x120\n" +
	"\x04memo\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x04memoB\b\n" +
	"\x06_priceB\vZ\tdemo2/apib\x06proto3"

var (
	file_notice_proto_rawDescOnce sync.Once
	file_notice_proto_rawDescData []byte
)

func file_notice_proto_rawDescGZIP() []byte {
	file_notice_proto_rawDescOnce.Do(func() {
		file_notice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notice_proto_rawDesc), len(file_notice_proto_rawDesc)))
	})
	return file_notice_proto_rawDescData
}

var file_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notice_proto_goTypes = []any{
	(*NoticeReaderRequest)(nil),    // 0: api.NoticeReaderRequest
	(*Book)(nil),                   // 1: api.Book
	(*wrapperspb.DoubleValue)(nil), // 2: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_notice_proto_depIdxs = []int32{
	2, // 0: api.Book.price2:type_name -> google.protobuf.DoubleValue
	3, // 1: api.Book.memo:type_name -> google.protobuf.StringValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notice_proto_init() }
func file_notice_proto_init() {
	if File_notice_proto != nil {
		return
	}
	file_notice_proto_msgTypes[0].OneofWrappers = []any{
		(*NoticeReaderRequest_Email)(nil),
		(*NoticeReaderRequest_Phone)(nil),
	}
	file_notice_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notice_proto_rawDesc), len(file_notice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notice_proto_goTypes,
		DependencyIndexes: file_notice_proto_depIdxs,
		MessageInfos:      file_notice_proto_msgTypes,
	}.Build()
	File_notice_proto = out.File
	file_notice_proto_goTypes = nil
	file_notice_proto_depIdxs = nil
}
